INSERT INTO CHARACTERS (ID, NAME, TYPE, NUMBER_POINT_LIVE, NUMBER_POINT_STRENGTH, NUMBER_POINT_DEFENSE, NUMBER_POINT_AGILITY, QUANTITY_DICE, QUANTITY_FACE_DICE)
VALUES (default, 'GUERREIRO', 'HERO', 20, 7, 5, 6, 1, 12);
INSERT INTO CHARACTERS (ID, NAME, TYPE, NUMBER_POINT_LIVE, NUMBER_POINT_STRENGTH, NUMBER_POINT_DEFENSE, NUMBER_POINT_AGILITY, QUANTITY_DICE, QUANTITY_FACE_DICE)
VALUES (default, 'BÁRBARO', 'HERO', 21, 10, 2, 5, 2, 8);
INSERT INTO CHARACTERS (ID, NAME, TYPE, NUMBER_POINT_LIVE, NUMBER_POINT_STRENGTH, NUMBER_POINT_DEFENSE, NUMBER_POINT_AGILITY, QUANTITY_DICE, QUANTITY_FACE_DICE)
VALUES (default, 'CAVALEIRO', 'HERO', 26, 6, 8, 3, 2, 6);
INSERT INTO CHARACTERS (ID, NAME, TYPE, NUMBER_POINT_LIVE, NUMBER_POINT_STRENGTH, NUMBER_POINT_DEFENSE, NUMBER_POINT_AGILITY, QUANTITY_DICE, QUANTITY_FACE_DICE)
VALUES (default, 'ORC', 'MONSTER', 42, 7, 1, 2, 3, 4);
INSERT INTO CHARACTERS (ID, NAME, TYPE, NUMBER_POINT_LIVE, NUMBER_POINT_STRENGTH, NUMBER_POINT_DEFENSE, NUMBER_POINT_AGILITY, QUANTITY_DICE, QUANTITY_FACE_DICE)
VALUES (default, 'GIGANTE', 'MONSTER', 34, 10, 4, 4, 2, 6);
INSERT INTO CHARACTERS (ID, NAME, TYPE, NUMBER_POINT_LIVE, NUMBER_POINT_STRENGTH, NUMBER_POINT_DEFENSE, NUMBER_POINT_AGILITY, QUANTITY_DICE, QUANTITY_FACE_DICE)
VALUES (default, 'LOBISOMEN', 'MONSTER', 34, 7, 4, 7, 2, 4);

INSERT INTO PLAYERS (ID, NAME, NUMBER_MATCHES, NUMBER_MATCHES_WON, NUMBER_MATCHES_LOST)
VALUES (default, 'PLAYER1', 20, 10, 10);
INSERT INTO PLAYERS (ID, NAME, NUMBER_MATCHES, NUMBER_MATCHES_WON, NUMBER_MATCHES_LOST)
VALUES (default, 'PLAYER2', 20, 10, 10);
INSERT INTO PLAYERS (ID, NAME, NUMBER_MATCHES, NUMBER_MATCHES_WON, NUMBER_MATCHES_LOST)
VALUES (default, 'PLAYER3', 20, 10, 10);
INSERT INTO PLAYERS (ID, NAME, NUMBER_MATCHES, NUMBER_MATCHES_WON, NUMBER_MATCHES_LOST)
VALUES (default, 'PLAYER4', 20, 10, 10);
INSERT INTO PLAYERS (ID, NAME, NUMBER_MATCHES, NUMBER_MATCHES_WON, NUMBER_MATCHES_LOST)
VALUES (default, 'PLAYER5', 20, 10, 10);
INSERT INTO PLAYERS (ID, NAME, NUMBER_MATCHES, NUMBER_MATCHES_WON, NUMBER_MATCHES_LOST)
VALUES (default, 'PLAYER6', 20, 10, 10);
INSERT INTO PLAYERS (ID, NAME, NUMBER_MATCHES, NUMBER_MATCHES_WON, NUMBER_MATCHES_LOST)
VALUES (default, 'PLAYER7', 20, 10, 10);
INSERT INTO PLAYERS (ID, NAME, NUMBER_MATCHES, NUMBER_MATCHES_WON, NUMBER_MATCHES_LOST)
VALUES (default, 'PLAYER8', 20, 10, 10);
INSERT INTO PLAYERS (ID, NAME, NUMBER_MATCHES, NUMBER_MATCHES_WON, NUMBER_MATCHES_LOST)
VALUES (default, 'PLAYER9', 20, 10, 10);
INSERT INTO PLAYERS (ID, NAME, NUMBER_MATCHES, NUMBER_MATCHES_WON, NUMBER_MATCHES_LOST)
VALUES (default, 'PLAYER10', 20, 10, 10);
INSERT INTO PLAYERS (ID, NAME, NUMBER_MATCHES, NUMBER_MATCHES_WON, NUMBER_MATCHES_LOST)
VALUES (default, 'PLAYER11', 20, 10, 10);

INSERT INTO GAMES (ID, GAME_DATE, GAME_TIME, GAME_PLAYER_NAME, GAME_CHARACTER_NAME, GAME_OPPONENT_NAME, GAME_INITIATIVE_NAME)
VALUES (default, '2023/08/14', '11:06', 'PLAYER1', 'GUERREIRO', 'GIGANTE', 'Character');
INSERT INTO GAMES (ID, GAME_DATE, GAME_TIME, GAME_PLAYER_NAME, GAME_CHARACTER_NAME, GAME_OPPONENT_NAME, GAME_INITIATIVE_NAME)
VALUES (default, '2023/08/14', '11:06', 'PLAYER1', 'GUERREIRO', 'GIGANTE', 'Character');
INSERT INTO GAMES (ID, GAME_DATE, GAME_TIME, GAME_PLAYER_NAME, GAME_CHARACTER_NAME, GAME_OPPONENT_NAME, GAME_INITIATIVE_NAME)
VALUES (default, '2023/08/14', '11:06', 'PLAYER1', 'GUERREIRO', 'GIGANTE', 'Character');
INSERT INTO GAMES (ID, GAME_DATE, GAME_TIME, GAME_PLAYER_NAME, GAME_CHARACTER_NAME, GAME_OPPONENT_NAME, GAME_INITIATIVE_NAME)
VALUES (default, '2023/08/14', '11:06', 'PLAYER2', 'GUERREIRO', 'GIGANTE', 'Character');
INSERT INTO GAMES (ID, GAME_DATE, GAME_TIME, GAME_PLAYER_NAME, GAME_CHARACTER_NAME, GAME_OPPONENT_NAME, GAME_INITIATIVE_NAME)
VALUES (default, '2023/08/14', '11:06', 'PLAYER2', 'GUERREIRO', 'GIGANTE', 'Character');
INSERT INTO GAMES (ID, GAME_DATE, GAME_TIME, GAME_PLAYER_NAME, GAME_CHARACTER_NAME, GAME_OPPONENT_NAME, GAME_INITIATIVE_NAME)
VALUES (default, '2023/08/14', '11:06', 'PLAYER3', 'GUERREIRO', 'GIGANTE', 'Character');
INSERT INTO GAMES (ID, GAME_DATE, GAME_TIME, GAME_PLAYER_NAME, GAME_CHARACTER_NAME, GAME_OPPONENT_NAME, GAME_INITIATIVE_NAME)
VALUES (default, '2023/08/14', '11:06', 'PLAYER3', 'GUERREIRO', 'GIGANTE', 'Character');
INSERT INTO GAMES (ID, GAME_DATE, GAME_TIME, GAME_PLAYER_NAME, GAME_CHARACTER_NAME, GAME_OPPONENT_NAME, GAME_INITIATIVE_NAME)
VALUES (default, '2023/08/14', '11:06', 'PLAYER4', 'GUERREIRO', 'GIGANTE', 'Character');
INSERT INTO GAMES (ID, GAME_DATE, GAME_TIME, GAME_PLAYER_NAME, GAME_CHARACTER_NAME, GAME_OPPONENT_NAME, GAME_INITIATIVE_NAME)
VALUES (default, '2023/08/14', '11:06', 'PLAYER4', 'GUERREIRO', 'GIGANTE', 'Character');
INSERT INTO GAMES (ID, GAME_DATE, GAME_TIME, GAME_PLAYER_NAME, GAME_CHARACTER_NAME, GAME_OPPONENT_NAME, GAME_INITIATIVE_NAME)
VALUES (default, '2023/08/14', '11:06', 'PLAYER5', 'GUERREIRO', 'GIGANTE', 'Character');
INSERT INTO GAMES (ID, GAME_DATE, GAME_TIME, GAME_PLAYER_NAME, GAME_CHARACTER_NAME, GAME_OPPONENT_NAME, GAME_INITIATIVE_NAME)
VALUES (default, '2023/08/14', '11:06', 'PLAYER5', 'GUERREIRO', 'GIGANTE', 'Character');
INSERT INTO GAMES (ID, GAME_DATE, GAME_TIME, GAME_PLAYER_NAME, GAME_CHARACTER_NAME, GAME_OPPONENT_NAME, GAME_INITIATIVE_NAME)
VALUES (default, '2023/08/14', '11:06', 'PLAYER6', 'GUERREIRO', 'GIGANTE', 'Character');
INSERT INTO GAMES (ID, GAME_DATE, GAME_TIME, GAME_PLAYER_NAME, GAME_CHARACTER_NAME, GAME_OPPONENT_NAME, GAME_INITIATIVE_NAME)
VALUES (default, '2023/08/14', '11:06', 'PLAYER6', 'GUERREIRO', 'GIGANTE', 'Character');
INSERT INTO GAMES (ID, GAME_DATE, GAME_TIME, GAME_PLAYER_NAME, GAME_CHARACTER_NAME, GAME_OPPONENT_NAME, GAME_INITIATIVE_NAME)
VALUES (default, '2023/08/14', '11:06', 'PLAYER7', 'GUERREIRO', 'GIGANTE', 'Character');
INSERT INTO GAMES (ID, GAME_DATE, GAME_TIME, GAME_PLAYER_NAME, GAME_CHARACTER_NAME, GAME_OPPONENT_NAME, GAME_INITIATIVE_NAME)
VALUES (default, '2023/08/14', '11:06', 'PLAYER7', 'GUERREIRO', 'GIGANTE', 'Character');
INSERT INTO GAMES (ID, GAME_DATE, GAME_TIME, GAME_PLAYER_NAME, GAME_CHARACTER_NAME, GAME_OPPONENT_NAME, GAME_INITIATIVE_NAME)
VALUES (default, '2023/08/14', '11:06', 'PLAYER8', 'GUERREIRO', 'GIGANTE', 'Character');
INSERT INTO GAMES (ID, GAME_DATE, GAME_TIME, GAME_PLAYER_NAME, GAME_CHARACTER_NAME, GAME_OPPONENT_NAME, GAME_INITIATIVE_NAME)
VALUES (default, '2023/08/14', '11:06', 'PLAYER8', 'GUERREIRO', 'GIGANTE', 'Character');
INSERT INTO GAMES (ID, GAME_DATE, GAME_TIME, GAME_PLAYER_NAME, GAME_CHARACTER_NAME, GAME_OPPONENT_NAME, GAME_INITIATIVE_NAME)
VALUES (default, '2023/08/14', '11:06', 'PLAYER9', 'GUERREIRO', 'GIGANTE', 'Character');
INSERT INTO GAMES (ID, GAME_DATE, GAME_TIME, GAME_PLAYER_NAME, GAME_CHARACTER_NAME, GAME_OPPONENT_NAME, GAME_INITIATIVE_NAME)
VALUES (default, '2023/08/14', '11:06', 'PLAYER9', 'GUERREIRO', 'GIGANTE', 'Character');
INSERT INTO GAMES (ID, GAME_DATE, GAME_TIME, GAME_PLAYER_NAME, GAME_CHARACTER_NAME, GAME_OPPONENT_NAME, GAME_INITIATIVE_NAME)
VALUES (default, '2023/08/14', '11:06', 'PLAYER10', 'GUERREIRO', 'GIGANTE', 'Character');
INSERT INTO GAMES (ID, GAME_DATE, GAME_TIME, GAME_PLAYER_NAME, GAME_CHARACTER_NAME, GAME_OPPONENT_NAME, GAME_INITIATIVE_NAME)
VALUES (default, '2023/08/14', '11:06', 'PLAYER10', 'GUERREIRO', 'GIGANTE', 'Character');
INSERT INTO GAMES (ID, GAME_DATE, GAME_TIME, GAME_PLAYER_NAME, GAME_CHARACTER_NAME, GAME_OPPONENT_NAME, GAME_INITIATIVE_NAME)
VALUES (default, '2023/08/14', '11:06', 'PLAYER10', 'GUERREIRO', 'GIGANTE', 'Character');

INSERT INTO SHIFTS (ID, GAME_ID, SHIFT_NUMBER, ATTACKER, ATTACK_POINTS, DEFENSE_POINTS, DAMAGE_POINTS, CHARACTER_LIVE_POINTS, OPPONENT_LIVE_POINTS)
VALUES (default, 1, 1, 'Character', 10, 10, 10, 10, 10);
INSERT INTO SHIFTS (ID, GAME_ID, SHIFT_NUMBER, ATTACKER, ATTACK_POINTS, DEFENSE_POINTS, DAMAGE_POINTS, CHARACTER_LIVE_POINTS, OPPONENT_LIVE_POINTS)
VALUES (default, 1, 2, 'Opponent', 10, 10, 10, 10, 10);
INSERT INTO SHIFTS (ID, GAME_ID, SHIFT_NUMBER, ATTACKER, ATTACK_POINTS, DEFENSE_POINTS, DAMAGE_POINTS, CHARACTER_LIVE_POINTS, OPPONENT_LIVE_POINTS)
VALUES (default, 2, 1, 'Character', 10, 10, 10, 10, 10);
INSERT INTO SHIFTS (ID, GAME_ID, SHIFT_NUMBER, ATTACKER, ATTACK_POINTS, DEFENSE_POINTS, DAMAGE_POINTS, CHARACTER_LIVE_POINTS, OPPONENT_LIVE_POINTS)
VALUES (default, 2, 2, 'Opponent', 10, 10, 10, 10, 10);
INSERT INTO SHIFTS (ID, GAME_ID, SHIFT_NUMBER, ATTACKER, ATTACK_POINTS, DEFENSE_POINTS, DAMAGE_POINTS, CHARACTER_LIVE_POINTS, OPPONENT_LIVE_POINTS)
VALUES (default, 3, 1, 'Character', 10, 10, 10, 10, 10);
INSERT INTO SHIFTS (ID, GAME_ID, SHIFT_NUMBER, ATTACKER, ATTACK_POINTS, DEFENSE_POINTS, DAMAGE_POINTS, CHARACTER_LIVE_POINTS, OPPONENT_LIVE_POINTS)
VALUES (default, 3, 2, 'Opponent', 10, 10, 10, 10, 10);
INSERT INTO SHIFTS (ID, GAME_ID, SHIFT_NUMBER, ATTACKER, ATTACK_POINTS, DEFENSE_POINTS, DAMAGE_POINTS, CHARACTER_LIVE_POINTS, OPPONENT_LIVE_POINTS)
VALUES (default, 4, 1, 'Character', 10, 10, 10, 10, 10);
INSERT INTO SHIFTS (ID, GAME_ID, SHIFT_NUMBER, ATTACKER, ATTACK_POINTS, DEFENSE_POINTS, DAMAGE_POINTS, CHARACTER_LIVE_POINTS, OPPONENT_LIVE_POINTS)
VALUES (default, 4, 2, 'Character', 10, 10, 10, 10, 10);
INSERT INTO SHIFTS (ID, GAME_ID, SHIFT_NUMBER, ATTACKER, ATTACK_POINTS, DEFENSE_POINTS, DAMAGE_POINTS, CHARACTER_LIVE_POINTS, OPPONENT_LIVE_POINTS)
VALUES (default, 5, 1, 'Opponent', 10, 10, 10, 10, 10);
INSERT INTO SHIFTS (ID, GAME_ID, SHIFT_NUMBER, ATTACKER, ATTACK_POINTS, DEFENSE_POINTS, DAMAGE_POINTS, CHARACTER_LIVE_POINTS, OPPONENT_LIVE_POINTS)
VALUES (default, 5, 2, 'Character', 10, 10, 10, 10, 10);
INSERT INTO SHIFTS (ID, GAME_ID, SHIFT_NUMBER, ATTACKER, ATTACK_POINTS, DEFENSE_POINTS, DAMAGE_POINTS, CHARACTER_LIVE_POINTS, OPPONENT_LIVE_POINTS)
VALUES (default, 6, 1, 'Opponent', 10, 10, 10, 10, 10);
INSERT INTO SHIFTS (ID, GAME_ID, SHIFT_NUMBER, ATTACKER, ATTACK_POINTS, DEFENSE_POINTS, DAMAGE_POINTS, CHARACTER_LIVE_POINTS, OPPONENT_LIVE_POINTS)
VALUES (default, 6, 2, 'Character', 10, 10, 10, 10, 10);
INSERT INTO SHIFTS (ID, GAME_ID, SHIFT_NUMBER, ATTACKER, ATTACK_POINTS, DEFENSE_POINTS, DAMAGE_POINTS, CHARACTER_LIVE_POINTS, OPPONENT_LIVE_POINTS)
VALUES (default, 7, 1, 'Opponent', 10, 10, 10, 10, 10);
INSERT INTO SHIFTS (ID, GAME_ID, SHIFT_NUMBER, ATTACKER, ATTACK_POINTS, DEFENSE_POINTS, DAMAGE_POINTS, CHARACTER_LIVE_POINTS, OPPONENT_LIVE_POINTS)
VALUES (default, 7, 2, 'Character', 10, 10, 10, 10, 10);
INSERT INTO SHIFTS (ID, GAME_ID, SHIFT_NUMBER, ATTACKER, ATTACK_POINTS, DEFENSE_POINTS, DAMAGE_POINTS, CHARACTER_LIVE_POINTS, OPPONENT_LIVE_POINTS)
VALUES (default, 8, 1, 'Opponent', 10, 10, 10, 10, 10);
INSERT INTO SHIFTS (ID, GAME_ID, SHIFT_NUMBER, ATTACKER, ATTACK_POINTS, DEFENSE_POINTS, DAMAGE_POINTS, CHARACTER_LIVE_POINTS, OPPONENT_LIVE_POINTS)
VALUES (default, 8, 2, 'Character', 10, 10, 10, 10, 10);
INSERT INTO SHIFTS (ID, GAME_ID, SHIFT_NUMBER, ATTACKER, ATTACK_POINTS, DEFENSE_POINTS, DAMAGE_POINTS, CHARACTER_LIVE_POINTS, OPPONENT_LIVE_POINTS)
VALUES (default, 9, 1, 'Opponent', 10, 10, 10, 10, 10);
INSERT INTO SHIFTS (ID, GAME_ID, SHIFT_NUMBER, ATTACKER, ATTACK_POINTS, DEFENSE_POINTS, DAMAGE_POINTS, CHARACTER_LIVE_POINTS, OPPONENT_LIVE_POINTS)
VALUES (default, 9, 2, 'Character', 10, 10, 10, 10, 10);
INSERT INTO SHIFTS (ID, GAME_ID, SHIFT_NUMBER, ATTACKER, ATTACK_POINTS, DEFENSE_POINTS, DAMAGE_POINTS, CHARACTER_LIVE_POINTS, OPPONENT_LIVE_POINTS)
VALUES (default, 10, 1, 'Opponent', 10, 10, 10, 10, 10);
INSERT INTO SHIFTS (ID, GAME_ID, SHIFT_NUMBER, ATTACKER, ATTACK_POINTS, DEFENSE_POINTS, DAMAGE_POINTS, CHARACTER_LIVE_POINTS, OPPONENT_LIVE_POINTS)
VALUES (default, 10, 2, 'Character', 10, 10, 10, 10, 10);
INSERT INTO SHIFTS (ID, GAME_ID, SHIFT_NUMBER, ATTACKER, ATTACK_POINTS, DEFENSE_POINTS, DAMAGE_POINTS, CHARACTER_LIVE_POINTS, OPPONENT_LIVE_POINTS)
VALUES (default, 11, 1, 'Opponent', 10, 10, 10, 10, 10);
INSERT INTO SHIFTS (ID, GAME_ID, SHIFT_NUMBER, ATTACKER, ATTACK_POINTS, DEFENSE_POINTS, DAMAGE_POINTS, CHARACTER_LIVE_POINTS, OPPONENT_LIVE_POINTS)
VALUES (default, 11, 2, 'Character', 10, 10, 10, 10, 10);
INSERT INTO SHIFTS (ID, GAME_ID, SHIFT_NUMBER, ATTACKER, ATTACK_POINTS, DEFENSE_POINTS, DAMAGE_POINTS, CHARACTER_LIVE_POINTS, OPPONENT_LIVE_POINTS)
VALUES (default, 12, 1, 'Opponent', 10, 10, 10, 10, 10);
INSERT INTO SHIFTS (ID, GAME_ID, SHIFT_NUMBER, ATTACKER, ATTACK_POINTS, DEFENSE_POINTS, DAMAGE_POINTS, CHARACTER_LIVE_POINTS, OPPONENT_LIVE_POINTS)
VALUES (default, 12, 2, 'Character', 10, 10, 10, 10, 10);
INSERT INTO SHIFTS (ID, GAME_ID, SHIFT_NUMBER, ATTACKER, ATTACK_POINTS, DEFENSE_POINTS, DAMAGE_POINTS, CHARACTER_LIVE_POINTS, OPPONENT_LIVE_POINTS)
VALUES (default, 13, 1, 'Opponent', 10, 10, 10, 10, 10);
INSERT INTO SHIFTS (ID, GAME_ID, SHIFT_NUMBER, ATTACKER, ATTACK_POINTS, DEFENSE_POINTS, DAMAGE_POINTS, CHARACTER_LIVE_POINTS, OPPONENT_LIVE_POINTS)
VALUES (default, 13, 2, 'Character', 10, 10, 10, 10, 10);
INSERT INTO SHIFTS (ID, GAME_ID, SHIFT_NUMBER, ATTACKER, ATTACK_POINTS, DEFENSE_POINTS, DAMAGE_POINTS, CHARACTER_LIVE_POINTS, OPPONENT_LIVE_POINTS)
VALUES (default, 14, 1, 'Opponent', 10, 10, 10, 10, 10);
INSERT INTO SHIFTS (ID, GAME_ID, SHIFT_NUMBER, ATTACKER, ATTACK_POINTS, DEFENSE_POINTS, DAMAGE_POINTS, CHARACTER_LIVE_POINTS, OPPONENT_LIVE_POINTS)
VALUES (default, 14, 2, 'Character', 10, 10, 10, 10, 10);
INSERT INTO SHIFTS (ID, GAME_ID, SHIFT_NUMBER, ATTACKER, ATTACK_POINTS, DEFENSE_POINTS, DAMAGE_POINTS, CHARACTER_LIVE_POINTS, OPPONENT_LIVE_POINTS)
VALUES (default, 15, 1, 'Opponent', 10, 10, 10, 10, 10);
INSERT INTO SHIFTS (ID, GAME_ID, SHIFT_NUMBER, ATTACKER, ATTACK_POINTS, DEFENSE_POINTS, DAMAGE_POINTS, CHARACTER_LIVE_POINTS, OPPONENT_LIVE_POINTS)
VALUES (default, 15, 2, 'Opponent', 10, 10, 10, 10, 10);
INSERT INTO SHIFTS (ID, GAME_ID, SHIFT_NUMBER, ATTACKER, ATTACK_POINTS, DEFENSE_POINTS, DAMAGE_POINTS, CHARACTER_LIVE_POINTS, OPPONENT_LIVE_POINTS)
VALUES (default, 16, 1, 'Character', 10, 10, 10, 10, 10);
INSERT INTO SHIFTS (ID, GAME_ID, SHIFT_NUMBER, ATTACKER, ATTACK_POINTS, DEFENSE_POINTS, DAMAGE_POINTS, CHARACTER_LIVE_POINTS, OPPONENT_LIVE_POINTS)
VALUES (default, 16, 2, 'Opponent', 10, 10, 10, 10, 10);
INSERT INTO SHIFTS (ID, GAME_ID, SHIFT_NUMBER, ATTACKER, ATTACK_POINTS, DEFENSE_POINTS, DAMAGE_POINTS, CHARACTER_LIVE_POINTS, OPPONENT_LIVE_POINTS)
VALUES (default, 17, 1, 'Character', 10, 10, 10, 10, 10);
INSERT INTO SHIFTS (ID, GAME_ID, SHIFT_NUMBER, ATTACKER, ATTACK_POINTS, DEFENSE_POINTS, DAMAGE_POINTS, CHARACTER_LIVE_POINTS, OPPONENT_LIVE_POINTS)
VALUES (default, 17, 2, 'Opponent', 10, 10, 10, 10, 10);
INSERT INTO SHIFTS (ID, GAME_ID, SHIFT_NUMBER, ATTACKER, ATTACK_POINTS, DEFENSE_POINTS, DAMAGE_POINTS, CHARACTER_LIVE_POINTS, OPPONENT_LIVE_POINTS)
VALUES (default, 18, 1, 'Character', 10, 10, 10, 10, 10);
INSERT INTO SHIFTS (ID, GAME_ID, SHIFT_NUMBER, ATTACKER, ATTACK_POINTS, DEFENSE_POINTS, DAMAGE_POINTS, CHARACTER_LIVE_POINTS, OPPONENT_LIVE_POINTS)
VALUES (default, 18, 2, 'Opponent', 10, 10, 10, 10, 10);
INSERT INTO SHIFTS (ID, GAME_ID, SHIFT_NUMBER, ATTACKER, ATTACK_POINTS, DEFENSE_POINTS, DAMAGE_POINTS, CHARACTER_LIVE_POINTS, OPPONENT_LIVE_POINTS)
VALUES (default, 19, 1, 'Character', 10, 10, 10, 10, 10);
INSERT INTO SHIFTS (ID, GAME_ID, SHIFT_NUMBER, ATTACKER, ATTACK_POINTS, DEFENSE_POINTS, DAMAGE_POINTS, CHARACTER_LIVE_POINTS, OPPONENT_LIVE_POINTS)
VALUES (default, 19, 2, 'Opponent', 10, 10, 10, 10, 10);
INSERT INTO SHIFTS (ID, GAME_ID, SHIFT_NUMBER, ATTACKER, ATTACK_POINTS, DEFENSE_POINTS, DAMAGE_POINTS, CHARACTER_LIVE_POINTS, OPPONENT_LIVE_POINTS)
VALUES (default, 20, 1, 'Character', 10, 10, 10, 10, 10);
INSERT INTO SHIFTS (ID, GAME_ID, SHIFT_NUMBER, ATTACKER, ATTACK_POINTS, DEFENSE_POINTS, DAMAGE_POINTS, CHARACTER_LIVE_POINTS, OPPONENT_LIVE_POINTS)
VALUES (default, 20, 2, 'Opponent', 10, 10, 10, 10, 10);
INSERT INTO SHIFTS (ID, GAME_ID, SHIFT_NUMBER, ATTACKER, ATTACK_POINTS, DEFENSE_POINTS, DAMAGE_POINTS, CHARACTER_LIVE_POINTS, OPPONENT_LIVE_POINTS)
VALUES (default, 21, 1, 'Character', 10, 10, 10, 10, 10);
INSERT INTO SHIFTS (ID, GAME_ID, SHIFT_NUMBER, ATTACKER, ATTACK_POINTS, DEFENSE_POINTS, DAMAGE_POINTS, CHARACTER_LIVE_POINTS, OPPONENT_LIVE_POINTS)
VALUES (default, 21, 2, 'Opponent', 10, 10, 10, 10, 10);
INSERT INTO SHIFTS (ID, GAME_ID, SHIFT_NUMBER, ATTACKER, ATTACK_POINTS, DEFENSE_POINTS, DAMAGE_POINTS, CHARACTER_LIVE_POINTS, OPPONENT_LIVE_POINTS)
VALUES (default, 22, 1, 'Character', 10, 10, 10, 10, 10);
INSERT INTO SHIFTS (ID, GAME_ID, SHIFT_NUMBER, ATTACKER, ATTACK_POINTS, DEFENSE_POINTS, DAMAGE_POINTS, CHARACTER_LIVE_POINTS, OPPONENT_LIVE_POINTS)
VALUES (default, 22, 2, 'Opponent', 10, 10, 10, 10, 10);
